#!/bin/bash

# 2018-04-01 00:34:25.0 +0200 / Gilles Quenot <gilles.quenot@sputnick.fr>
# wrapper script to have newline delimited output on Xpath querys

args=( "$@" )
if [[ $@ == *--xpath* ]]; then
    # iterate over positional parameters
    for ((i=0; i<${#args}; i++)); do
        if [[ ${args[i]} == --xpath ]]; then
            xpath="${args[i+1]}"
            unset args[i+1]
            unset args[i]
        fi
    done
    if [[ $file == - ]]; then
        /usr/bin/xmllint "$@"
    else
        /usr/bin/xmllint "${args[@]}" --shell <<< "cat $xpath" | sed '1d;$d;s/^ ------- *$//;/^$/d; s/^ *//'
    fi
else
    /usr/bin/xmllint "$@"
fi
